export const cards = [
  {
    id: 1,
    image: '/A1.jpg',
    question: ['<strong>Q1:</strong> Identify the pointed structure and mention its arterial supply?'],
    comment: [
      '- Structure: fibrous pericardium lined by parietal layer of serous pericardium.',
      '- Arterial supply:',
      '1) Pericardiophrenic artery.',
      '2) Descending thoracic aorta (pericardial branches).',
      '3) Internal thoracic artery (pericardial branches).',
    ],
  },
  {
    id: 2,
    image: '/A1.jpg',
    question: ['<strong>Q2:</strong> Identify the pointed structure and mention its nerve supply?'],
    comment: [
      '- Structure: fibrous pericardium.',
      '- Nerve supply:',
      '1) Left and right phrenic nerves.',
      '2) Intercostal nerves.',
    ],
  },
  {
    id: 3,
    image: '/A2.jpg',
    question: ['<strong>Q3:</strong> Identify the pointed structure and mention its sinuses?'],
    comment: [
      '- Structure: fibrous pericardium.',
      '- Sinuses:',
      '1) Transverse sinus.',
      '2) Oblique sinus.',
    ],
  },
  {
    id: 4,
    image: '/A2.jpg',
    question: ['<strong>Q4:</strong> Identify the pointed structure and mention its ligaments?'],
    comment: [
      '- Structure: fibrous pericardium.',
      '- Ligaments:',
      '1) Superior and inferior sternopericardial ligaments.',
      '2) Pericardiophrenic ligament.',
    ],
  },
  {
    id: 5,
    image: '/A3.jpg',
    question: ['<strong>Q5:</strong> Identify the numbering areas?'],
    comment: [
      '- Opened pericardium showing the anterior surface of the heart and great vessels:',
      '1) Fibrous pericardium.',
      '2) Right ventricle.',
      '3) Pulmonary trunk.',
      '4) Ascending aorta.',
      '5) Arch of aorta.',
      '6) Superior vena cava (SVC).',
      '7) Ligamentum arteriosum.',
    ],
  },
  {
    id: 6,
    image: '/A4.jpg',
    question: ['<strong>Q5:</strong> Identify the numbering areas?'],
    comment: [
      '- Opened pericardium showing the anterior surface of the heart and great vessels:',
      '8) Inferior vena cava (IVC).',
      '9) Pulmonary trunk and valve.',
      '10) Ascending aorta and valve.',
      '11) Left pulmonary veins.',
      '12) Oblique sinus.',
    ],
  },
  {
    id: 7,
    image: '/A5.jpg',
    question: ['<strong>Q6:</strong> Identify the area related to the white arrow?'],
    comment: [
        '- White arrow: Transverse sinus of serous pericardium.'
    ],
  },
  {
    id: 8,
    image: '/A5.jpg',
    question: ['<strong>Q7:</strong> Identify the area related to the yellow arrow?'],
    comment: [
        '- Yellow arrow: Oblique sinus of serous pericardium.'
    ],
  },
  {
    id: 9,
    image: '/A5.jpg',
    question: ['<strong>Q8:</strong> Identify the numbering areas??'],
    comment: [
      '1) IVC.',
      '2) Right pulmonary veins.',
      '3) SVC.',
      '4) Ascending aorta.',
      '5) Arch of aorta.',
      '6) Brachiocephalic artery (innominate artery).',
      '7) Left common carotid artery.',
      '8) Left subclavian artery.',
      '9) Pulmonary trunk.',
      '10) Right border of heart made by right atrium and covered by fibrous pericardium.',
    ],
  },
  {
    id: 10,
    image: '/A6.jpg',
    question: ['<strong>Q9:</strong> Identify the pointed numbers?'],
    comment: [
      '1) Right atrium.',
      '2) Right ventricle.',
      '3) Left ventricle.',
      '4) Arch of aorta.',
      '5) Brachiocephalic artery.',
      '6) Left common carotid artery.',
      '7) Left subclavian artery.',
    ],
  },
  {
    id: 11,
    image: '/A7.jpg',
    question: ['<strong>Q9:</strong> Identify the pointed numbers?'],
    comment: [
      '8. Left atrium',
      '9. Left ventricle',
      '10. Atrioventricular groove or coronary sulcus',
    ],
  },
  {
    id: 12,
    image: '/A8.jpg',
    question: ['<strong>Q10:</strong> Identify the pointed structures?'],
    comment: [
      'A. Right coronary artery',
      'B. Left coronary giving circumflex branch',
      'C. Left anterior descending or anterior interventricular artery',
      'D. Arch of aorta',
    ],
  },
  {
    id: 13,
    image: '/A10.jpg',
    question: ['<strong>Q12:</strong> Identify the pointed structures?'],
    comment: [
      'A. Left ventricle',
      'B. Trabeculae carneae and papillary muscles',
      'C. Interventricular septum',
      'D. Right ventricle',
    ],
  },
  {
    id: 14,
    image: '/A11.jpg',
    question: ['<strong>Q13:</strong> Identify the numbering areas?'],
    comment: [
      'Coronal plane section of heart',
      '1. Apex of heart',
      '2. Left ventricular wall',
      '3. Papillary muscle',
      '4. Interventricular septum',
      '5. Right ventricle',
      '6. Opening of IVC',
      '7. Opening of SVC',
      '8. Pulmonary trunk',
      '9. Ascending aorta',
      '10. Arch of aorta',
    ],
  },
  {
    id: 15,
    image: '/A12.jpg',
    question: ['<strong>Q14:</strong> Identify the pointed structures?'],
    comment: [
      '1. Tricuspid valve',
      '2. Right coronary artery',
      '3. Aorta and aortic valve',
      '4. Pulmonary artery & valve',
      '5. Left coronary artery',
      '6. Mitral valve',
    ],
  },
  {
    id: 16,
    image: '/A13.jpg',
    question: ['<strong>Q15:</strong> Identify the cardiac anomales?'],
    comment: ['<!-- TODO: أضف الإجابة هنا -->'],
  },
  {
    id: 17,
    image: '/A14.jpg',
    question: ['<strong>Q16:</strong> Identify the cardiac anomales?'],
    comment: ['<!-- TODO: أضف الإجابة هنا -->'],
  },
  {
    id: 18,
    image: '/A15.jpg',
    question: ['<strong>Q16:</strong> Identify the cardiac anomales?'],
    comment: ['<!-- TODO: أضف الإجابة هنا -->'],
  },
  {
    id: 19,
    image: '/A16.jpg',
    question: ['<strong>Q17:</strong> Identify the cardiac anomales?'],
    comment: ['<!-- TODO: أضف الإجابة هنا -->'],
  },
  {
    id: 20,
    image: '/A17.jpg',
    question: ['<strong>Q18:</strong> Identify the cardiac anomales?'],
    comment: ['<!-- TODO: أضف الإجابة هنا -->'],
  },
  {
    id: 21,
    image: '/A18.jpg',
    question: ['<strong>Q19:</strong> Identify the pointed structure and mention two branches?'],
    comment: [
      '- Structure: Arch of aorta.',
      '- Branches:',
      '1) Brachiocephalic artery.',
      '2) Left common carotid artery.',
      '3) Left subclavian artery.',
    ],
  },
  {
    id: 22,
    image: '/A18.jpg',
    question: ['<strong>Q20:</strong> Identify the pointed structure and mention the level of its termination?'],
    comment: [
        '- Structure: Arch of aorta.<br>- Termination: at the lower border of the body of thoracic vertebra T4.'
    ],
  },
  {
    id: 23,
    image: '/A19.jpg',
    question: ['<strong>Q21:</strong> Identify the pointed structure and mention two tributaries?'],
    comment: [
      '- Structure: Left brachiocephalic vein.',
      '- Tributaries:',
      '1) Left internal jugular vein.',
      '2) Left subclavian vein.',
    ],
  },
  {
    id: 24,
    image: '/A19.jpg',
    question: ['<strong>Q22:</strong> Identify the pointed structure and mention its termination?'],
    comment: [
        '- Structure: Left brachiocephalic vein.<br>- Termination: unites with right brachiocephalic vein at the level of right 1st costal cartilage to form the SVC.'
    ],
  },
  {
    id: 25,
    image: '/A20.jpg',
    question: ['<strong>Q23:</strong> Identify the numbering areas?'],
    comment: [
      '1. Celiac trunk',
      '2. Common hepatic artery',
      '3. Superior mesenteric artery',
      '4. IVC',
      '5. Right common carotid',
      '6. External carotid',
      '7. Inferior mesenteric artery',
      '8. Abdominal aorta',
      '9. Splenic artery',
      '10. Left renal artery',
    ],
  },
  {
    id: 26,
    image: '/A25.jpg',
    question: ['<strong>Q31:</strong> Identify the pointed structure (1) and mention two branches?'],
    comment: [
      'Right common carotid artery',
      '1. External carotid artery',
      '2. Internal carotid artery',
    ],
  },
  {
    id: 27,
    image: '/A25.jpg',
    question: ['<strong>Q32:</strong> Identify the pointed structure (2) and mention the level of its beginning?'],
    comment: [
      'Internal carotid artery',
      'at the upper border of the thyroid cartilage, at the level of the 4th cervical vertebra (C4), as a terminal branch of the common carotid artery.',
    ],
  },
  {
    id: 28,
    image: '/A25.jpg',
    question: ['<strong>Q33:</strong> Identify the pointed structure (3) and mention two branches?'],
    comment: [
      'External carotid artery',
      '1. Superior thyroid artery',
      '2. Lingual artery',
      '3. Occipital artery',
      '4. Maxillary artery',
      '5. Fascial artery',
    ],
  },
];
